namespace: todoapp-ns
secrets:
  - key: SECRET_KEY
    value: "secret_value"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
image:
  repository: my-repo/todoapp
  tag: latest
nodeAffinity:
  key: app
  values:
    - mysql
hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50
  memoryUtilization: 50
pv:
  capacity: 1Gi
pvc:
  requests:
    storage: 1Gi
serviceAccountName: todoapp-sa
